version: '2'

services:
  redis:
    image: 'redis:3.2.11'
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=adminadmin



